version: '2'

services:

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: docker
    ports:
      - '3306:3306'
    volumes:
      - ./src/test/resources/database/initdb:/docker-entrypoint-initdb.d